//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOrderDOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_id { get; set; }
        public System.DateTime order_date { get; set; }
        public int Amount { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> salesperson_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SalesPerson SalesPerson { get; set; }
    }
}
